# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='escorts')),
                ('description', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('measurements', models.CharField(blank=True, max_length=140)),
                ('dress_size', models.CharField(blank=True, max_length=140)),
                ('complexion', models.CharField(blank=True, max_length=140)),
                ('build', models.CharField(blank=True, max_length=140)),
                ('height', models.CharField(blank=True, max_length=140)),
                ('hair', models.CharField(blank=True, max_length=140)),
                ('eye', models.CharField(blank=True, max_length=140)),
                ('nationality', models.CharField(blank=True, max_length=140)),
                ('languages', models.CharField(blank=True, max_length=140)),
                ('sexual_orientation', models.CharField(blank=True, max_length=140)),
                ('incall_outcall', models.CharField(blank=True, max_length=140)),
                ('background', models.ImageField(blank=True, upload_to='')),
                ('primary_color', models.CharField(blank=True, max_length=6)),
                ('background_color', models.CharField(blank=True, max_length=6)),
                ('redirect', models.URLField(blank=True, max_length=140)),
                ('allow_follow', models.BooleanField(default=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('popular', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escort_profile.Category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
