# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0001_initial'),
        ('escort_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='girl',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='girls.Girl', verbose_name='escortgirl'),
        ),
    ]
