# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort_profile', '0002_escort_girl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
    ]
