# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort_profile', '0003_auto_20160708_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='london-escorts/%Y/%m/%d', verbose_name='Face'),
        ),
    ]
