# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort_profile', '0004_escort_photo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='cheap-escort-london/%Y/%m/%d', verbose_name='Pic 3'),
        ),
        migrations.AlterField(
            model_name='escort',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cheap-escort-london/%Y/%m/%d', verbose_name='Pic 1'),
        ),
        migrations.AlterField(
            model_name='escort',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='cheap-escort-london/%Y/%m/%d', verbose_name='Pic 2'),
        ),
    ]
