# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 20:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort_profile', '0006_auto_20160709_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='available_today',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='escort',
            name='rates',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
